SCSSをGulp管理化に移動して整理
yutakawano/digsmile pull request #10
Opened 2021-06-27 01:41 UTC by yutakawano

ブランチ：compile-scss
各タスクが完了しましたのでご確認お願いいたします。

2021-06-27 05:12 UTC, S-Yamamoto3215 requested changes

2021-06-27 05:12 UTC, S-Yamamoto3215 commented on .gitignore
> +/css/
ファイルを持たず、空のディレクトリを保持するには必要なものがあります。
ヒント：`.gitkeep`

また、上記`node_modules`と体裁を揃えるなら先頭の`/`はいらないです。
このcssディレクトリ以下のcssファイルのみを監視外にしたいので、その記述も追加しておいてください。
ヒント：ワイルドカード

2021-06-28 11:22 UTC, yutakawano commented on .gitignore
> +/css/
> ファイルを持たず、空のディレクトリを保持するには必要なものがあります。

cssフォルダに`.gitkeep`を置き、`.gitignore`に`!.gitkeep`を記述しました。

> node_modulesと体裁を揃えるなら先頭の/はいらないです。
このcssディレクトリ以下のcssファイルのみを監視外にしたいので、その記述も追加しておいてください。

`.gitignore`内の記述`/css/`を`css/*`に修正しました。

2021-06-28 12:13 UTC, S-Yamamoto3215 commented on .gitignore
> +/css/
## ワイルドカードについて

ヒントで「ワイルドカード」という単語を出したのですが
それを採用しなかった理由はありますか？
ワイルドカードを使うことで.gitignoreに`!.gitkeep`を書く必要はなくなります。

## .gitkeepについて
なぜ新規に作成するのではなく、`src/scss/`から`css/`に移動させたのでしょうか？
意図していないのであれば、commitする前にstatusでgitのステージング状態は確認しましたか？

2021-06-29 12:07 UTC, yutakawano commented on .gitignore
> +/css/
> ヒントで「ワイルドカード」という単語を出したのですが
> それを採用しなかった理由はありますか？

.gitignoreにcss/*を追加したことで、cssフォルダ内をgit監視外にできると思いました。
ただ、その後.gitkeepとは一体何なのか？ということで調べたところ、gitでは空ディレクトリをaddできないという記事を見つけ.gitkeepを使う必要があると考えました。
その際、空のディレクトリはgit監視したいが、中のファイルは監視しない方法として.gitignoreに!.gitkeepを記述せよ、という記事を見つけたため、!.gitkeepも記述する必要があると考えて.gitignoreに!.gitkeepを記述し、add,commitしました。

> ワイルドカードを使うことで.gitignoreに!.gitkeepを書く必要はなくなります。

.gitkeepについて勘違いしていたようで、cssフォルダに.gitkeepを作成するだけで良かった(!.gitkeepを記述する必要はなかった)ということですね。

> なぜ新規に作成するのではなく、src/scss/からcss/に移動させたのでしょうか？

cssフォルダ内に新規で.gitkeepを作成しましたが、その後何故かscssフォルダ内にも.gitkeepが作成されており、勘違いしてscssに作ってしまったと思い、scss内の.gitkeepを削除しました。
なので、移動では無く、cssフォルダに.gitkeepを作成し、いつの間にか作成されていたscssフォルダ内の.gitkeepを削除した、ということになります。

> 意図していないのであれば、commitする前にstatusでgitのステージング状態は確認しましたか？

おっしゃる通り、意図しない挙動でしたが、statusの確認が漏れたかもしれません。

2021-06-29 12:19 UTC, S-Yamamoto3215 commented on .gitignore
> +/css/
> .gitkeepについて勘違いしていたようで、cssフォルダに.gitkeepを作成するだけで良かった(!.gitkeepを記述する必要はなかった)ということですね。

これは間違っています。
`.gitkeep`を追加するだけだとあまり良くないかも。
私が言いたいのはワイルドカードを使うことでcss/以下にあるcssファイルのみを監視外にできますよね？
ということです。
今は
`css/*` => cssディレクトリ以下のすべて
となっていますが、少し書き換えることでcssディレクトリ以下のcssファイルのみを監視から外せます。

> その後何故かscssフォルダ内にも.gitkeepが作成されており

違います。これは間違って作ったものでも無くて
私が以前作っておいて、masterにマージしていたものです。
仮に新規で作ったのだとしたら、git status時にnew add fileとしてgitに含まれるはずです。
しかし、削除して差分が出るということは、「元からあったものを消そうとしている」ということになります。
加えて、同じファイル名のものが別のフォルダで作られたので、githubはファイルが移動したと認知しているというわけです。

2021-06-29 23:40 UTC, yutakawano commented on .gitignore
> +/css/
> cssディレクトリ以下のcssファイルのみを監視から外せます。

.gitignoreにcss/*.cssを記述することでcssファイルのみを監視外にできます。

> .gitkeepについて

理解が及ばずすみません。今回はgitkeepを追加したりする必要は無かったということでしょうか？

2021-06-29 23:48 UTC, S-Yamamoto3215 commented on .gitignore
> +/css/
> .gitignoreにcss/*.cssを記述する

これはOKです👍

> 理解が及ばずすみません。

なにがわかってないのか説明できますか？
私が言いたいのは単純で

> その後何故かscssフォルダ内にも.gitkeepが作成されており、勘違いしてscssに作ってしまったと思い、scss内の.gitkeepを削除しました。
なので、移動では無く、cssフォルダに.gitkeepを作成し、いつの間にか作成されていたscssフォルダ内の.gitkeepを削除した

とおっしゃっていたので
「そうではなくて、それは元からあったんですよ」ということです。

正直、`src/scss/.gitkeep`についてはもうあってもなくてもいいので
消しても、消さなくても良いのですが
ちゃんと理解してgitの操作をしているのか確認のために問うてる感じです。

2021-06-30 10:33 UTC, yutakawano commented on .gitignore
> +/css/
なるほど、、.gitkeepはすでにあったんですね。。
git statusやgit logで今の状態を確実に理解しながら進めるようにします！

ちなみに理解が曖昧な部分は.gitkeepの用途です。
gitでは空のディレクトリをaddできない、という仕様？のため、今回で言えば、cssフォルダをaddする際には.gitkeepをcssフォルダ内に作成した状態にしないとaddできない、つまり、cssフォルダをaddするために.gitkeepを作成する必要があった。
という認識でお間違い無いですか？
となると、scssフォルダにgitkeepを作成した理由は何故でしょうか？
scssフォルダにはstyle.scssというファイルがあり、空ではないので.gitkeepが無くてもaddできるのでは無いかと考えました。

以上、、ご確認お願いします！

2021-06-30 11:27 UTC, S-Yamamoto3215 commented on .gitignore
> +/css/
> gitでは空のディレクトリをaddできない、という仕様？のため、今回で言えば、cssフォルダをaddする際には.gitkeepをcssフォルダ内に作成した状態にしないとaddできない、つまり、cssフォルダをaddするために.gitkeepを作成する必要があった。

あってます👍

> となると、scssフォルダにgitkeepを作成した理由は何故でしょうか？
scssフォルダにはstyle.scssというファイルがあり、空ではないので.gitkeepが無くてもaddできるのでは無いかと考えました。

この認識もあっています。
が、私がgulpの設定を諸々しmasterにマージした内容の中に、style.scssの移動は含まれていないはずです。
つまり、今回のプルリクで`src/scss/`以下にstyle.scssを**ゆうたさんが**移動させるまでは空だったはずです。

ファイルを移動させたことで確かに不要だし、今回のプルリクで削除してもOKです。
ですが、なぜこんなに質問したのかというと

### そのあたりのことをしっかりと理解した上で、削除することを選んだのかどうか、意図せず削除してしまっているのではないかどうかを確認したかった

というのが主な理由になります。

2021-06-30 11:37 UTC, yutakawano commented on .gitignore
> +/css/
意図してダミーを作成していた、ということでしょうか？？

2021-06-30 11:39 UTC, S-Yamamoto3215 commented on .gitignore
> +/css/
> あえてダミー(.gitkeep)をscssフォルダに作成していた

あえてではなくて、

- 僕が設定した時はフォルダが空だった => つまり必要
- 今回のプルリクの作業でcssフォルダからsrc/scssにstyle.scssをゆうたさんが移動させて => 不要になった

ということです。

2021-06-30 12:07 UTC, yutakawano commented on .gitignore
> +/css/
なるほど、理解しました！

2021-07-01 12:15 UTC, yutakawano commented
諸々修正しまして、プルリクが意図した内容に更新されていることを確認できました。
ご確認お願いいたします！

2021-07-01 12:48 UTC, S-Yamamoto3215 approved these changes

2021-07-01 12:48 UTC, merged

2021-07-01 12:50 UTC, S-Yamamoto3215 commented
本プルリクの該当issue
#8 

問題ないのでマージしました